development:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_development
  pool: 5
  username: capellajuris
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_test
  pool: 5
  username: capellajuris
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_staging
  pool: 5
  username: capellajuris
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_production
  pool: 5
  username: capellajuris
  password:
