development:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_test
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_staging
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: capellajuris_production
  pool: 5
