defaults: &defaults
  admin:
    username: <%= ENV["ADMIN_USERNAME"] %>
    password: <%= ENV["ADMIN_PASSWORD"] %>
    flickr_set: 72157628108442555
  amazon:
    access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AMAZON_SECRET_ACCESS_KEY"] %>
  flickr:
    api_key: <%= ENV["FLICKR_API_KEY"] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
